
version: 2
.conan-steps: &conan-steps
  steps:
    - checkout
    - run:
        name: Update Conan package
        command: |
          chmod +x .circleci/install.sh
          .circleci/install.sh
    - run:
        name: Build recipe
        command: |
          chmod +x .circleci/run.sh
          .circleci/run.sh
        environment:
          CONAN_REFERENCE: "print/0.0.0"
          CONAN_USERNAME: "user"
          CONAN_CHANNEL: "channel"
          
jobs:

  gcc-49:
      docker:
        - image: lasote/conangcc49
      environment:
        - CONAN_GCC_VERSIONS: "4.9"
      <<: *conan-steps

  gcc-5:
      docker:
        - image: lasote/conangcc5
      environment:
        - CONAN_GCC_VERSIONS: "5"
      <<: *conan-steps

  gcc-6:
      docker:
        - image: lasote/conangcc6
      environment:
        - CONAN_GCC_VERSIONS: "6"
      <<: *conan-steps

  gcc-7:
      docker:
        - image: lasote/conangcc7
      environment:
        - CONAN_GCC_VERSIONS: "7"
      <<: *conan-steps


workflows:
  version: 2
  build_and_test:
    jobs:
      - gcc-49
      - gcc-5
      - gcc-6
      - gcc-7


